export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";
export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const FETCH_FILE_LOADER = "FETCH_FILE_LOADER";
export const FETCH_FILE_SUCCESS = "FETCH_FILE_SUCCESS";
export const FETCH_FILE_FAILURE = "FETCH_FILE_FAILURE";
