export const FILE_SELECT = "FILE_SELECT";
export const FILE_UPLOAD_REQUEST = "FILE_UPLOAD_REQUEST";
export const FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS";
export const FILE_UPLOAD_FAILURE = "FILE_UPLOAD_FAILURE";
export const FILE_CLEAR = "FILE_CLEAR";

export const CLEAR_MESSAGE = "CLEAR_MESSAGES";
